name: build-branch

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: kagekirin/gha-py-toolbox/.github/workflows/blender-build.yml@main
    with:
      blender-release: ${{ vars.BLENDER_RELEASE }}
      blender-version: ${{ vars.BLENDER_VERSION }}
      blender-platform: ${{ vars.BLENDER_PLATFORM }}
      blender-url: ${{ vars.BLENDER_URL }}
      blender-path: ${{ vars.BLENDER_PATH }}
      manifest-toml: ${{ vars.MANIFEST_TOML }}
    secrets: inherit


  test-tag-release:
    permissions:
      contents: write
      packages: read
    needs:
    - build
    uses: kagekirin/gha-py-toolbox/.github/workflows/github-release.yml@main
    with:
      dry-run: true
    secrets: inherit
